-- Optional seed for `supabase db reset`.
--
-- Auth-linked rows (`public.profiles`, students, teachers, lessons, …) cannot be inserted here
-- because `seed.sql` runs **before** `npm run seed:dev-users` creates `auth.users`.
--
-- **Scheduling / calendar / credits dev fixtures** are applied by the Node seed (same command as test users):
--   npm run seed:sync-env && npm run seed:dev-users
--
-- See `scripts/seed-dev-scheduling-fixtures.ts` and `docs/testing/test-accounts.md` (Test scenarios).
